### ISSUE TITLE
strange Standard_ConstructionError 

### ISSUE THREAD

**Issue by hmeyer** [jay3sh/cadmium#4]
please look at this:

`````` #!/usr/bin/python
import sys
sys.path.append('./src')
from cadmium import *
u = Box(62,62,100, center=True) + Sphere(19).translate(-31,-31,-31)```

when run with current HEAD, I get:
```Traceback (most recent call last):
  File "examples/fail.py", line 5, in <module>
    u = Box(62,62,100, center=True) + Sphere(19).translate(-31,-31,-31)
  File "./src/cadmium/solid.py", line 50, in __add__
    union = BRepAlgoAPI_Fuse(self.shape, other.shape).Shape()
  File "/usr/lib/pymodules/python2.7/OCC/BRepAlgoAPI.py", line 222, in __init__
    _BRepAlgoAPI.BRepAlgoAPI_Fuse_swiginit(self,_BRepAlgoAPI.new_BRepAlgoAPI_Fuse(*args))
RuntimeError: Standard_ConstructionError```
``````

**Comment by jay3sh** [comment]
The error happens inside OCC. I do see such errors occasionally, but don't know the cause.

**Comment by hmeyer** [comment]
Could you please help me creating a minimal example which reproduces this
error? Than I try to escalate to python-occ.
Am 30.12.2011 03:25 schrieb "Jayesh Salvi" <
reply@reply.github.com
